name: capi-kamaji-vsphere
version: 0.2.5
appVersion: 1.32.0
description: A Helm chart for deploying a Kamaji Tenant Cluster on vSphere using Cluster API
  and Kamaji.
icon: https://raw.githubusercontent.com/kubernetes/cloud-provider-vsphere/master/docs/vmware_logo.png
type: application
apiVersion: v2
maintainers:
  - name: Clastix Labs
    email: authors@clastix.labs
keywords:
  - kubernetes
  - cluster-api
  - kamaji
  - vsphere
home: https://kamaji.clastix.io
sources:
  - https://github.com/clastix/cluster-api-kamaji-vsphere
annotations:
  artifacthub.io/links: |
    - name: Clastix Labs
      url: https://github.com/clastix
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: "Full Lifecycle"
  artifacthub.io/changes: |
    - kind: commit
      description: Initial commit.
